Description: Template that uses the lambda-backed custom resource provider to create a test custom resource.
Parameters:
  ResourceProviderLambdaArn:
    Type: String
    Description: ARN of the resource provider lambda.

Resources:
  ResourceInstance:
    Type: Custom::Resource
    Properties:
      ServiceToken: !Ref ResourceProviderLambdaArn